---
dev_addr: "0.0.0.0:8001"
edit_uri: "edit/main/nautobot-plugin-ssot-aci/docs"
site_name: "Nautobot SSoT APIC Documentation"
site_url: "https://nautobot-plugin-ssot-aci.readthedocs.io/"
repo_url: "https://github.com/nautobot/nautobot-plugin-ssot-aci"
python:
  install:
    - requirements: "docs/requirements.txt"
theme:
  name: "readthedocs"
  navigation_depth: 4
  hljs_languages:
    - "django"
    - "yaml"
extra_css:
  - "extra.css"
markdown_extensions:
  - "admonition"
  - toc:
      permalink: true
nav:
  - Introduction: "index.md"
  - Installation and Configuration: "install_configure.md"
  - Development: "development.md"
  - Usage: "usage.md"
